spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.config.import=aws-secretsmanager:/config/edgp
spring.cloud.aws.region.static=ap-southeast-1
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082

allowed.origin=${ALLOWED_ORIGIN}

aws.sqs.queue.audit.url=${AUDIT_SQS_URL}
audit.activity.type.prefix=Admin-

jwt.private.key=${JWT_PRIVATE_KEY}
jwt.public.key=${JWT_PUBLIC_KEY}

aes.secret.key={AES_SECRET_KEY}

pentest.enable=${PENTEST_ENABLE}
secure.flag.enable=${SECURE_ENABLE}
demo.flag.enable= ${DEMO_ENABLE}

notification.api.url= ${NOTIFICATION_URL}